import React from 'react';
import { PageWrapper, PageHeader } from './PageComponents';

interface MinigameProps {
  playerImageUrl: string;
  obstacleImageUrl: string;
  onClose: () => void;
  playSound: (player: () => void) => void;
}

// FIX: Added a component implementation to resolve the "not a module" error in ImageGeneratorPage.tsx.
export const Minigame: React.FC<MinigameProps> = ({
  playerImageUrl,
  obstacleImageUrl,
  onClose,
}) => {
  return (
    <PageWrapper>
      <PageHeader title="AI Minigame" onBack={onClose} />
      <main id="main-content" className="w-full max-w-lg flex flex-col items-center gap-6 font-sans">
        <p className="text-center">A mini-game would be here using the generated assets!</p>
        <div className="flex gap-4">
          <div className="text-center">
            <h3 className="font-press-start text-brand-cyan">Player</h3>
            <img src={playerImageUrl} alt="Player character" className="w-32 h-32 object-contain border-2 border-brand-light bg-black/20" style={{ imageRendering: 'pixelated' }} />
          </div>
          <div className="text-center">
            <h3 className="font-press-start text-brand-cyan">Obstacle</h3>
            <img src={obstacleImageUrl} alt="Obstacle" className="w-32 h-32 object-contain border-2 border-brand-light bg-black/20" style={{ imageRendering: 'pixelated' }} />
          </div>
        </div>
        <p className="text-sm text-center text-brand-light/80">
            This is a placeholder for a dynamic game generated by AI.
        </p>
      </main>
    </PageWrapper>
  );
};
